### ISSUE TITLE
Embed images in output html

### ISSUE THREAD

**Issue by ngraham20** [ngraham20/rusty-gfm-html#4]
Add the ability to b64 embed an image into the html.

To do this, first convert the image into b64

```bash
base64 example.png
```

then embed it into the html with a src ref. In the example below, the encoded text would be a PNG image; however, this can be done with other types of data as well.

```html
<img src="data:image/png;base64, ENCODED_TEXT"/>
```

Note that this will result in a _much_ bigger file, but a file that needs not be zipped along with source images.

**Comment by khushi2031** [comment]
#5 
<html>
<body>
<code>
<span style="color: #000000">Hello&nbsp;world!&nbsp;
<span style="color: #0000BB">&lt;?php&nbsp;phpinfo</span>
<span style="color: #007700">();&nbsp;</span>
<span style="color: #0000BB">?&gt;</span>
</span>
</code>
</body>
</html>

**Comment by ngraham20** [comment]
This shouldn't be too complicated, as a simple regex could work.

The regex would look for

```html
<img src="FILENAME"/>
```

And simply replace `FILENAME` with `data:image/FILETYPE;base64, ENCODED_TEXT`, keeping the double quotes.

The file type should be parsed from the image.
